name: biocosmos_b200
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - accelerate
  - bidict
  - biopython
  - ipykernel
  - numpy
  - pandas
  - pillow
  - pygbif
  - scikit-learn
  - seaborn
  - tensorboard
  - tqdm
  - requests
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - torchaudio==2.7.1+cu128
      - transformers
      - datasets
      - "timm>=1.0.0"
      - "open-clip-torch>=2.24.0"
      - ftfy
      - regex
      - huggingface_hub
