# Exponential LR Scheduler
exp:
  args:
    lr_min: 1.0e-8
  args_sched:
    gamma: 0.98  # decay rate

# Plateau LR Scheduler
plat:  # may also want to tweak threshold / eps
  args:
    reset_best_valid: true  # (true) reset best validation score after LR drop to avoid early plateauing
    valid_type:       loss  # options: {loss, perf}
  args_sched:
    factor:   0.61803398875  # golden ratio
    patience: 1
    cooldown: 1
    min_lr:   1.0e-7

# Cosine LR Scheduler
cos:
  args:
    dummy: null
  args_sched:
    T_max:   5  # half-period
    eta_min: 1.0e-7

# Cosine Warm-Restarts LR Scheduler
coswr:
  args:
    dummy: null
  args_sched:
    T_0:     7  # period
    eta_min: 1.0e-7

# Cosine X Exponential LR Scheduler
cosXexp:
  args:
    gamma:      0.98
    period:     10
    peak_ratio: 10
    lr_nom_min: 5.0e-7

# Cosine Warm-Restarts X Exponential LR Scheduler
coswrXexp:
  args:
    gamma:      0.98
    period:     10
    peak_ratio: 10
    lr_nom_min: 5.0e-7