# *** split_name, model_type, loss_type, non_causal are overridden if rdpath_trial is specified ***
rdpath_trial: null  # which trial to load from (set null for original model)
# rdpath_trial: artifacts/class_imb_sig/mp_posneg/42
save_crit:    comp  # options: comp / img2img; model save criterion (only applicable if rdpath_trial != null)

# split_name: S29-42
split_name: P38-42

batch_size:  2048  # 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768

dev:
  verbose_batch_loss: false

arch:
  model_type: siglip_vitb16  # common options: {bioclip, clip_vitb16, siglip_vitb16}
  non_causal: false

loss:
  type:  bce  # options: {infonce1, infonce2, bce, mse, huber}
  sim:   cos  # options: {cos, geo1, geo2}
  targ:  multipos  # options: {aligned, multipos, hierarchical, phylogenetic}
  wting: false
  focal: false

text_preps: bioclip_sci